Update Features: Document how to deprecate a Feature
devcontainers/spec pull request #157
Opened 2022-12-13 17:34 UTC by samruddhikhandale

Addresses - https://github.com/devcontainers/spec/issues/155

2022-12-13 22:02 UTC, joshspicer requested changes

2022-12-13 22:02 UTC, joshspicer commented on docs/specs/devcontainer-features-distribution.md
> +To deprecate an existing Feature, move the Feature's [source code](#source-code) out of the `src` folder or delete the source code. This will ensure that the Feature's metadata is not added to the [d
This isn't quite "deprecating", more "orphaning" the Feature and not supplying updates.  We (or a supporting tool) would have no idea that the user isn't planning on updating the Feature anymore (a supporting tool would not have the information it needs to display a deprecation warning, for example).

I think the concept of "deprecation" is more tied to the aliasing property (https://github.com/devcontainers/spec/issues/146) you're looking into.

2022-12-14 22:34 UTC, samruddhikhandale commented on docs/specs/devcontainer-features-distribution.md
> +To deprecate an existing Feature, move the Feature's [source code](#source-code) out of the `src` folder or delete the source code. This will ensure that the Feature's metadata is not added to the [d
I wrote this with an assumption that as soon as they commit their changes to the repo, the Action will auto run to `publish` the packages 🤔 

But it's a good point to clarify that 👍 I'll update.

2022-12-15 17:30 UTC, samruddhikhandale commented
Closing as no longer needed.

2022-12-15 17:30 UTC, closed without merging