fix: alllow trialing comma in JSON schema
devcontainers/spec pull request #458
Opened 2024-04-20 15:27 UTC by popsu

[Sorry :pray: if this is not the right way to do this, I just got here when I was looking how to silence 'Trailing comma' warnings in VS Code when editing a `devcontainer.json` file]

Currently a `devcontainer.json` with trailing commas works.

Either the schema or implementation is wrong, since they don't match. Changing the schema is probably easier, since changing the implementation would probably break many devcontainers.

2024-04-22 23:01 UTC, samruddhikhandale approved these changes
Looks like an acceptable change to me!

2024-09-26 07:36 UTC, chrmarti requested changes
We previously disallowed it: https://github.com/devcontainers/spec/pull/24#issuecomment-1091846135

2024-09-26 10:30 UTC, popsu commented
> We previously disallowed it: [#24 (comment)](https://github.com/devcontainers/spec/pull/24#issuecomment-1091846135)

The implementation allows it tho. My issue is that the implementation doesn't match spec and thus I get some warnings about invalid files. Sure it's not that big of an issue, but maybe other peopled had the same small issue :sweat_smile:

But I guess I'll just close this since it's not that big of a deal in the end, and seems like it's not that clear-cut how all this 'JSONC' even works and how are different editors using it.

2024-09-26 10:30 UTC, closed without merging

2025-02-25 08:15 UTC, Badboyboom commented on schemas/devContainer.base.schema.json
> +	"allowTrailingCommas": true,
popsu:patch-1